export const projectList = [
        {
            name: "Basic Landing Page",
            imageSrc: "./src/assets/basic-landing-page.png",
            description: "A basic landing page built with HTML and CSS that can be used as a template for future projects.",
            github: "https://github.com/coder-guy-pete/landing_page",
            skills: ["HTML", "CSS"],
        },
        {
            name: "CSS Cheat Sheet",
            imageSrc: "src/assets/css-cheat-sheet.png",
            description: "This webpage utilized HTML, CSS, and JavaScript to create a cheat sheet for CSS snippets that can be used in other applications and services.",
            github: "https://github.com/coder-guy-pete/CSS_snippet_cheat_sheet",
            skills: ["HTML", "CSS", "JavaScript"],
        },
        {
            name: "Recipe Planner",
            imageSrc: "src/assets/recipe-planner.png",
            description: "A web application that allows users to store recipes that they have found online, and create their own recipes. Users can also schedule their meals for the week, and add one-off grocery items to their shopping list.",
            github: "https://github.com/coder-guy-pete/recipe-planner",
            skills: ["HTML", "Tailwind CSS", "JavaScript", "Node.js", "NPM"],
        },
        {
            name: "Portfolio Generator",
            imageSrc: "src/assets/portfolio-generator.png",
            description: "A command-line tool that generates an HTML portfolio page from user input.",
            github: "https://github.com/coder-guy-pete/portfolio-generator",
            skills: ["HTML", "JavaScript", "Node.js", "NPM", "Inquirer.js"],
        },
        {
            name: "Zoo Tracking App",
            imageSrc: "src/assets/zoo-tracking-app.gif",
            description: "A command-line application to keep track of Animals and Employees of a Zoo. The application allows users to add, view, and update animals and employees.",
            github: "https://github.com/coder-guy-pete/Zoo-tracking-app",
            skills: ["TypeScript", "Node.js", "NPM", "Inquirer.js"],
        },
        {
            name: "Readme Generator",
            imageSrc: "src/assets/readme-generator.png",
            description: "A command-line application that dynamically generates a professional README.md file from a user's inputs.",
            github: "https://github.com/coder-guy-pete/Readme-generator",
            skills: ["JavaScript", "Node.js", "NPM", "Inquirer.js"],
        },
        {
            name: "Vehicle Builder",
            imageSrc: "src/assets/vehicle-builder.gif",
            description: "A command-line application that builds and uses cars and has additional options for motorbikes and trucks.",
            github: "https://github.com/coder-guy-pete/Vehicle-Builder",
            skills: ["TypeScript", "Node.js", "NPM", "Inquirer.js"],
        },
        {
            name: "National Parks Indexer",
            imageSrc: "src/assets/national-park-indexer.gif",
            description: "A web application that queries the National Parks API and displays information on the parks available in a given State.",
            github: "https://github.com/coder-guy-pete/national-parks-index",
            skills: ["HTML", "CSS", "TypeScript", "Vite", "Node.js", "NPM", "Express.js", "APIs"],
        },
        {
            name: "Weather Dashboard",
            imageSrc: "src/assets/weather-dashboard.gif",
            description: "A web application that calls the OpenWeather API and renders the current weather and a 5-day forecast for a given city.",
            github: "https://github.com/coder-guy-pete/weather-dashboard",
            skills: ["HTML", "Bootstrap CSS", "Vite", "TypeScript", "Node.js", "NPM", "Express.js", "APIs"],
        },
        {
            name: "Employee Tracker",
            imageSrc: "src/assets/employee-manager.gif",
            description: "A command-line application that manages a company's employee data.",
            github: "https://github.com/coder-guy-pete/employee-tracker",
            skills: ["TypeScript", "Vite", "Node.js", "NPM", "Inquirer.js", "PostgreSQL"],
        },
        {
            name: "This Portfolio!",
            imageSrc: "src/assets/portfolio.png",
            description: "A React web application that showcases my projects and skills and provides a way to contact me.",
            github: "",
            skills: ["React", "Chakra UI", "Vite", "React-Router", "Node.js", "NPM"],
        },
    ];